version: 1.0.{build}
branches:
  only:
  - master
  - testing
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./Movies/Movies.sln
build:
  project: ./Movies/Movies.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
services:
  - mssql2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: RLJebaQd1odW41Xjp8NfzPluwdAe90LH4b/6otoua7TwWVEt1Z+wSCy+vEBJkVwC

after_test: 
        - Movies\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[Movies*]*" -target:"Movies\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:multiple /process:Separate Movies\Movies.Tests.UnitTests\bin\Debug\Movies.Tests.UnitTests.dll Movies\Movies.Tests.IntegrationTests\bin\Debug\Movies.Tests.IntegrationTests.dll" -output:cover.xml

        - Movies\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml